version: 2.1

executors:
  default:
    docker:
      - image: cimg/base:stable

jobs:
  deploy-to-gcp:
    executor: default
    steps:
      - checkout

      - run:
          name: Install Google Cloud SDK
          command: |
            # Update package lists and install prerequisites
            sudo apt update && sudo apt install -y curl apt-transport-https ca-certificates gnupg

            # Import Google Cloud public key and store it in a keyring file
            curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg

            # Add Google Cloud SDK repository using signed-by to keyring
            echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | sudo tee /etc/apt/sources.list.d/google-cloud-sdk.list

            # Update and install google-cloud-sdk
            sudo apt update && sudo apt install -y google-cloud-sdk

      - run:
          name: Authenticate to Google Cloud using Workload Identity Federation
          command: |
            # Replace with your values
            PROJECT_ID="sylvan-hydra-464904-d9"
            WIF_PROVIDER="projects/57920515119/locations/global/workloadIdentityPools/circleci-pool/providers/circleci-provider"
            SERVICE_ACCOUNT_EMAIL="circleci-vm-deployer@$PROJECT_ID.iam.gserviceaccount.com"

            gcloud iam workload-identity-pools create-cred-config $WIF_PROVIDER \
              --service-account=$SERVICE_ACCOUNT_EMAIL \
              --output-file=credentials.json

            export GOOGLE_APPLICATION_CREDENTIALS="credentials.json"
            export GOOGLE_CLOUD_PROJECT=$PROJECT_ID

      - run:
          name: Deploy application to GCP VM
          command: |
            PROJECT_ID="sylvan-hydra-464904-d9"
            ZONE="asia-south1-c"
            VM_NAME="my-vm"

            gcloud config set project $PROJECT_ID

            # Check if VM exists
            if ! gcloud compute instances describe $VM_NAME --zone $ZONE >/dev/null 2>&1; then
              echo "VM does not exist. Creating..."
              gcloud compute instances create $VM_NAME \
                --zone $ZONE \
                --machine-type e2-medium \
                --tags http-server \
                --image-family debian-11 \
                --image-project debian-cloud \
                --metadata startup-script='#! /bin/bash
                  sudo apt update
                  sudo apt install -y python3-pip
                  pip3 install flask
                  cat \<< EOF > app.py
                  from flask import Flask
                  app = Flask(__name__)
                  @app.route("/")
                  def hello():
                      return "Hello from CircleCI and GCP VM!"
                  if __name__ == "__main__":
                      app.run(host="0.0.0.0", port=8080)
                  EOF
                  nohup python3 app.py &'
            else
              echo "VM already exists. Skipping creation."
            fi

      - run:
          name: Open firewall for port 8080
          command: |
            if ! gcloud compute firewall-rules describe allow-8080 >/dev/null 2>&1; then
              gcloud compute firewall-rules create allow-8080 \
                --allow tcp:8080 \
                --target-tags http-server \
                --description="Allow port 8080 access"
            else
              echo "Firewall rule for port 8080 already exists."
            fi

      - run:
          name: Print VM External IP
          command: |
            EXTERNAL_IP=$(gcloud compute instances describe my-vm --zone asia-south1-c \
              --format='get(networkInterfaces[0].accessConfigs[0].natIP)')
            echo "Your application is deployed at http://$EXTERNAL_IP:8080"

workflows:
  deploy:
    jobs:
      - deploy-to-gcp
